### ISSUE TITLE
Issue: Highlight Sorted Column with Background Color Change

### ISSUE THREAD

**Issue by Khushboo1324** [X-DIABLO-X/LEADERBOARD#30]
Currently, when sorting a table, there is no visual cue indicating which column has been sorted. Adding a background color change to the sorted column will improve usability by allowing users to quickly identify the active sorting column.
@X-DIABLO-X 
please assign me this task!!

**Comment by AryenMukundam** [comment]
To highlight the sorted column with a background color change, we can add a class to the specific column's cells in the sortTable function. 
please assign me this task @X-DIABLO-X
