### ISSUE TITLE
Unresponsive Mobile Design

### ISSUE THREAD

**Issue by techSaswata** [X-DIABLO-X/LEADERBOARD#6]
The leaderboard is not optimized for mobile screens, leading to layout issues on smaller devices.
These improvements could

**Comment by AryenMukundam** [comment]
To make your leaderboard more mobile-responsive, here are some additional tweaks and adjustments to optimize spacing, alignment, and layout flexibility on small screens. These will ensure a smoother experience on devices under 600px wide.
