### ISSUE TITLE
Enhance Leaderboard with Overall Stats Display

### ISSUE THREAD

**Issue by Vimal290704** [X-DIABLO-X/LEADERBOARD#7]
To improve the usability and insights provided by the leaderboard, we propose adding an overall stats section above the leaderboard. This section would provide users with high-level statistics about the leaderboard's content.

Please assign me this task @X-DIABLO-X

**Comment by AryenMukundam** [comment]
To enhance this code, we can add the following improvements:

Sorting the Leaderboard: Sort the user's array by a specific rating to make the leaderboard more meaningful.
Total Rating Column: Add a column for the total rating across platforms, which could be useful for ranking.
Dynamic Color Style: Add CSS classes to apply colors based on rating levels.
Table Headers: Create a dynamic table header to improve readability and avoid hardcoding headers.
Responsiveness: Add basic responsive styles for mobile devices.

Please assign me this task @X-DIABLO-X

**Comment by AryenMukundam** [comment]
We can add several enhancements to make this leaderboard more comprehensive such as Adding Testcases (Handle Multiple Users, Negative and Edge Case Scenarios Sorting Check, Score Reset)
Please assign me this task @X-DIABLO-X
